apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: product-service
data:
  POSTGRES_DB: "products"
  POSTGRES_USER: "postgres"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"

---
apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
  namespace: product-service
type: Opaque
stringData:
  POSTGRES_PASSWORD: "haslo"
  SPRING_DATASOURCE_PASSWORD: "haslo"
