apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-service

resources:
  - namespace.yaml
  - configmap-secret.yaml
  - postgres-statefulset.yaml
  - zookeeper-deployment.yaml
  - kafka-statefulset.yaml
  - product-service-deployment.yaml
  - integration-service-deployment.yaml
  - ingress.yaml

images:
  - name: product-service
    newName: product-service
    newTag: latest
  - name: integration-service
    newName: integration-service
    newTag: latest

commonLabels:
  managed-by: kustomize

commonAnnotations:
  deployment.kubernetes.io/created: "2025"
